# Generated by Django 4.2.16 on 2025-10-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google account ID for OAuth authentication', max_length=255, null=True, unique=True),
        ),
    ]
