# Generated by Django 4.2.16 on 2025-10-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='session_token',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
