# Generated by Django 4.2.16 on 2025-10-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_google_id_delete_usersession'),
        ('authentication', '0004_recreate_usersession'),
    ]

    operations = [
    ]
